name: PR Workflow

on:
  pull_request:
    branches:
      - main # Trigger on PRs targeting the `main` branch

jobs:
  pr-job:
    name: Job triggered by PR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Random exit
        run: |
          number=$((RANDOM % 2))
          if [ $number -eq 0 ]; then
            echo "Even number: $number"
            exit 0
          else
            echo "Odd number: $number"
            exit 1
          fi

  another-pr-job:
    name: Another job triggered by PR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run a script
        run: echo "This is another job triggered by PR"

  dependent-job:
    name: Job triggered by PR jobs
    runs-on: ubuntu-latest
    needs:
      - pr-job
      - another-pr-job
    steps:
      - name: Perform dependent actions
        run: echo "This job runs after the PR jobs complete"
