name: PR Workflow

on:
  pull_request:
    branches:
      - main # Trigger on PRs targeting the `main` branch

jobs:
  pr-job:
    name: Job triggered by PR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run tests
        run: echo "Running tests for the PR"

  dependent-job:
    name: Job triggered by PR job
    runs-on: ubuntu-latest
    needs: pr-job # This job runs after `pr-job`
    steps:
      - name: Perform dependent actions
        run: echo "This job runs after the PR job completes"
